name: Deployment

on:
  push:
    branches:
      - master
      - develop

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: notify
        uses: appleboy/telegram-action@master
        env:
          CHAT: ${{ secrets.TELEGRAM_TO }}
          TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        run: |
          curl -s -X POST https://api.telegram.org/bot$TOKEN/sendMessage?chat_id=$CHAT -F text="$GITHUB_ACTOR on branch $GITHUB_REF"

      - name: Rsync
        run: |
          set -eu
          mkdir "$HOME/.ssh"
          echo "${{ secrets.PRIVATE_KEY }}" > "$HOME/.ssh/key"
          chmod 600 "$HOME/.ssh/key"
          rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" \
            --archive --compress --omit-dir-times \
            --exclude /deploy_key \
            --exclude /.git/ \
            --exclude /.github/ \
            --exclude /node_modules/ \
            ./ deploy@cv.bikmansurov.ru:/var/www/html/bikmansurov/cv/
        continue-on-error: true
